### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by nil-bsa2021** [nil-bsa2021/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by nil-odessa** [comment]
'''
<table id="timeline">
<tr>
<th>Year</th>
<th>Date</th>
<th>Type</th>
<th>Description</th>
</tr>
<tr><td>2005</td><td>07-Apr</td><td>Product</td><td>The initial version of Git, a version control system with support for data integrity, is released. Git would come to power GitHub.</td></tr>
<tr><td>2007</td><td>01-Oct</td><td>Company</td><td>Development of the GitHub platform begins.</td></tr>
<tr><td>2008</td><td>08-Feb</td><td>Company</td><td>GitHub is founded.</td></tr>
<tr><td>2008</td><td></td><td>Product</td><td>Bitbucket launches.</td></tr>
<tr><td>2008</td><td>22-Feb</td><td>Product</td><td>GitHub launches its company blog. In the announcement blog post, GitHub notes that per-project wikis have also launched.</td></tr>
<tr><td>2008</td><td>April</td><td>Product</td><td>Tom Preston-Werner, Chris Wanstrath, and PJ Hyett launch the GitHub website after having made it available a few months prior as a beta release.</td></tr>
<tr><td>2008</td><td>21-Jul</td><td>Product</td><td>GitHub launches Gist, a pastebin-style service with versioning.</td></tr>
<tr><td>2008</td><td>05-Nov</td><td>Product</td><td>The initial version of Jekyll, a static site generator, is released by GitHub CEO Tom Preston-Werner. Jekyll would come to power GitHub Pages.</td></tr>
<tr><td>2008</td><td>18-Dec</td><td>Product</td><td>GitHub announces GitHub Pages, a way for users to create custom websites.</td></tr>
<tr><td>2008</td><td>18-Jun</td><td>Userbase</td><td>Reddit joins GitHub.</td></tr>
<tr><td>2008</td><td>09-Jul</td><td>Userbase</td><td>Yahoo! joins GitHub.</td></tr>
<tr><td>2008</td><td>14-Dec</td><td>Userbase</td><td>The Sunlight Foundation, an American 501(c)(3) nonpartisan, nonprofit organization that advocates for open government, joins GitHub. By September 2010, the foundation would have 97 software projects hosted on GitHub.</td></tr>
<tr><td>2009</td><td>24-Feb</td><td>Growth</td><td>GitHub team members announce, in a talk at Yahoo! headquarters, that within the first year of being online, GitHub has accumulated over 46,000 public repositories, 17,000 of which were formed in the previous month alone. At this time, about 6,200 repositories have been forked at least once and 4,600 have been merged.</td></tr>
<tr><td>2009</td><td>27-Jul</td><td>Growth</td><td>Tom Preston-Werner announces that GitHub has grown to host 90,000 unique public repositories, 12,000 having been forked at least once, for a total of 135,000 repositories.</td></tr>
<tr><td>2009</td><td>05-Jul</td><td>Growth</td><td>GitHub reaches 100,000 users.</td></tr>
<tr><td>2009</td><td>20-Apr</td><td>Product</td><td>GitHub completes its transition to use GitHub Flavored Markdown on the site. GitHub Flavored Markdown is a variant of the Markdown markup language.</td></tr>
<tr><td>2009</td><td>14-Dec</td><td>Product</td><td>The initial commit to the Semantic Versioning repository is made by Tom Preston-Werner.</td></tr>
<tr><td>2009</td><td>29-Jan</td><td>Userbase</td><td>Twitter joins GitHub.</td></tr>
<tr><td>2009</td><td>01-Apr</td><td>Userbase</td><td>Facebook joins GitHub.</td></tr>
<tr><td>2010</td><td>01-Jul</td><td>Product</td><td>Ruby and JavaScript become the most popular languages on GitHub, with 19% and 17% of the hosted code, respectively.</td></tr>
<tr><td>2010</td><td>January</td><td>Company</td><td>GitHub Inc started to operate GitHub.</td></tr>
<tr><td>2010</td><td>24-Jul</td><td>Growth</td><td>GitHub hits 1 million hosted repositories. Of these repositories, 60% are regular repositories while the remaining 40% are Gists.</td></tr>
<tr><td>2010</td><td>10-Mar</td><td>Product</td><td>GitHub introduces Compare View, a feature that allows users to compare commits in a Git repository.In July, GitHub would add support for comparing across repositories.</td></tr>
<tr><td>2010</td><td>12-Aug</td><td>Product</td><td>GitHub announces that its per-project wikis are now backed by Git. The company also releases Gollum, the software powering these wikis.[33] On the same day, Gollum is declared to be version 1.0.0.</td></tr>
<tr><td>2010</td><td>29-Dec</td><td>Userbase</td><td>Pinterest joins GitHub.</td></tr>
<tr><td>2011</td><td>October</td><td>Competition</td><td>GitLab launches.</td></tr>
<tr><td>2011</td><td>02-Jun</td><td>Growth</td><td>ReadWriteWeb reports that GitHub has surpassed SourceForge, Google Code, and CodePlex in total number of commits for the period January to May 2011.</td></tr>
<tr><td>2011</td><td>23-Jun</td><td>Growth</td><td>At this time, GitHub has 33 employees.</td></tr>
<tr><td>2011</td><td>20-Apr</td><td>Growth</td><td>GitHub announces that it is hosting 2 million repositories.</td></tr>
<tr><td>2011</td><td>19-Apr</td><td>Product</td><td>GitHub releases Redcarpet, a Markdown parsing library based on Upskirt.</td></tr>
<tr><td>2011</td><td>15-Aug</td><td>Product</td><td>GitHub begins using the Ace code editor when editing files on the web interface.</td></tr>
<tr><td>2011</td><td>11-Oct</td><td>Product</td><td>The initial version (version 1.0.0) of Hubot, a chatbot developed by GitHub and written in CoffeeScript, is released.</td></tr>
<tr><td>2011</td><td>01-Nov</td><td>Product</td><td>GitHub launches GitHub Enterprise. GitHub Enterprise is similar to GitHub's public service but is designed for use by large-scale enterprise software development teams where the enterprise wishes to host their repositories behind a corporate firewall.</td></tr>
<tr><td>2012</td><td>10-Sep</td><td>Company</td><td>GitHub experiences service outage due to a poor database migration.</td></tr>
<tr><td>2012</td><td>18-Oct</td><td>Censorship</td><td>GitHub goes down due to a distributed denial of service attack.</td></tr>
<tr><td>2012</td><td>01-Jul</td><td>Company</td><td>GitHub receives $100 million in a series of investment, primarily from Andreessen Horowitz.</td></tr>
<tr><td>2012</td><td>09-Jul</td><td>Company</td><td>Peter Levine, general partner at GitHub's investor Andreessen Horowitz, states that GitHub has been growing revenue at 300% annually.</td></tr>
<tr><td>2012</td><td>13-Dec</td><td>Growth</td><td>At this time, GitHub has 139 employees.</td></tr>
<tr><td>2012</td><td>17-Jan</td><td>Userbase</td><td>Google joins GitHub.</td></tr>
<tr><td>2012</td><td>06-Apr</td><td>Userbase</td><td>The United States Consumer Financial Protection Bureau announces that it will open source the software it writes or contracts with a third-party to write. The agency decides to host its source code on GitHub.</td></tr>
<tr><td>2012</td><td>01-Aug</td><td>Userbase</td><td>The source code for the petitioning system We the People as well as the mobile apps White House for iOS and White House for Android are released on GitHub.</td></tr>
<tr><td>2013</td><td>21-Jan</td><td>Censorship</td><td>GitHub is blocked in China using DNS hijacking. Confirming the block, a spokesperson for GitHub says: "It does appear that we're at least being partly blocked by the Great Firewall of China". The block would be lifted on January 23, 2013 after an online protest on Sina Weibo.</td></tr>
<tr><td>2013</td><td>26-Jan</td><td>Censorship</td><td>GitHub users in China experience a man-in-the-middle attack in which attackers could have possibly intercepted traffic between the site and its users in China. The mechanism of the attack is through a fake SSL certificate. Users attempting to access GitHub received a warning of an invalid SSL certificate, which due to being signed by an unknown authority was quickly detected.</td></tr>
<tr><td>2013</td><td>22-Dec</td><td>Growth</td><td>At this time, GitHub has 234 employees.</td></tr>
<tr><td>2013</td><td>23-May</td><td>Growth</td><td>GitHub reaches 3.5 million users and 6 million repositories.</td></tr>
<tr><td>2013</td><td>07-Aug</td><td>Growth</td><td>GitHub reaches 7 million projects by their users.</td></tr>
<tr><td>2013</td><td>23-Dec</td><td>Growth</td><td>GitHub announces it has reached 10 million repositories.</td></tr>
<tr><td>2013</td><td>September</td><td>Growth</td><td>GitHub reaches 4 million active users.</td></tr>
<tr><td>2013</td><td>03-Jan</td><td>Product</td><td>GitHub introduces ZeroClipboard to the site, which allows for copying long lines of text and hashes with a single click.</td></tr>
<tr><td>2013</td><td>07-Jan</td><td>Product</td><td>GitHub launches Contributions, an addition to user profile pages that shows which repositories the user has been active in, as well as a calendar of activities.</td></tr>
<tr><td>2013</td><td>15-Feb</td><td>Product</td><td>GitHub open-sources Boxen, a tool that automates setting up macOS machines.</td></tr>
<tr><td>2013</td><td>April</td><td>Product</td><td>GitHub adds support for the STL file format for 3D modeling.</td></tr>
<tr><td>2013</td><td>05-Apr</td><td>Product</td><td>GitHub moves GitHub Pages to a dedicated domain, github.io. GitHub cites security reasons for the migration: to remove "potential vectors for cross domain attacks targeting the main github.com session" and mitigate phishing attempts. This migration reserves github.com for GitHub itself.</td></tr>
<tr><td>2013</td><td>31-May</td><td>Product</td><td>GitHub announces the release of Octokit, a set of client libraries for working with the GitHub API.</td></tr>
<tr><td>2013</td><td>15-Jul</td><td>Product</td><td>GitHub launches the ChooseALicense.com website to help users choose a free and open-source software license.</td></tr>
<tr><td>2013</td><td>15-Jul</td><td>Product</td><td>The initial version of Electron (at the time called Atom Shell) is released by GitHub.</td></tr>
<tr><td>2013</td><td>14-Jan</td><td>Growth</td><td>GitHub reaches 3 million total users. At this time, GitHub also has almost 5 million repositories.</td></tr>
<tr><td>2013</td><td>09-May</td><td>Userbase</td><td>United States president Barack Obama signs Executive Order 13642, "Making Open and Machine Readable the New Default for Government Information". As part of this new Open Data Policy, data is released on GitHub.</td></tr>
<tr><td>2013</td><td>20-Dec</td><td>Userbase</td><td>Facebook publishes a blog post about its progress in open-source software. At the time, Facebook has over 90 Git repositories hosted on GitHub.</td></tr>
<tr><td>2013</td><td>late in the year</td><td>Userbase</td><td>Microsoft joins GitHub.</td></tr>
<tr><td>2014</td><td>16-May</td><td>Company</td><td>The Crunchies announces that GitHub is a winner in Best Bootstrapped Startup.</td></tr>
<tr><td>2014</td><td>06-Jan</td><td>Company</td><td>Easel, a browser-based web design tool, announces that it has been acquired by GitHub. GitHub would announce the acquisition several days later.</td></tr>
<tr><td>2014</td><td>02-Dec</td><td>Censorship</td><td>Roscomnadzor, Russia's regulatory agency, blocks GitHub for hosting various copies of a suicide manual. Because GitHub uses HTTPS, which encrypts data between a user's computer and GitHub, internet service providers (ISP) are forced to block the whole website instead of the pages in question. Complying ISPs included Beeline, MTS, MGTS, and Megafon. Maxim Ksenzov, the Deputy Head of the Roscomnadzor, said in a statement that the block was due to GitHub not complying with earlier takedown requests for the manual on October 10, 2014. GitHub was also momentarily blocked on October 2, 2014 until the original copy of the manual was deleted.</td></tr>
<tr><td>2014</td><td>31-Dec</td><td>Censorship</td><td>GitHub is blocked in India (along with 31 other Websites) over pro-ISIS content posted by users. On 10 January 2015, GitHub would be unblocked. Again, on 12 Sep 2015, GitHub would be blocked all over India.</td></tr>
<tr><td>2014</td><td>17-Mar</td><td>Company</td><td>GitHub programmer Julie Ann Horvath alleges that founder and CEO Tom Preston-Werner and his wife Theresa engaged in a pattern of harassment against her that led to her leaving the company.</td></tr>
<tr><td>2014</td><td>April</td><td>Company</td><td>GitHub releases a statement denying Horvath's allegations of harassment.n k  However, following an internal investigation, GitHub would confirm the claims. GitHub's CEO Chris Wanstrath would write on the company blog, "The investigation found Tom Preston-Werner in his capacity as GitHub's CEO acted inappropriately, including confrontational conduct, disregard of workplace complaints, insensitivity to the impact of his spouse's presence in the workplace, and failure to enforce an agreement that his spouse should not work in the office."CEO Preston-Werner would subsequently resign from the company.</td></tr>
<tr><td>2014</td><td>17-Jul</td><td>Company</td><td>GitHub introduces a middle management system. Prior to this, GitHub was a flat organization.</td></tr>
<tr><td>2014</td><td>12-Feb</td><td>Company</td><td>WhatsApp sends a DMCA takedown request to GitHub for alleged copyright and trademark violations.</td></tr>
<tr><td>2014</td><td>09-Jan</td><td>Product</td><td>GitHub launches their Bug Bounty Program.</td></tr>
<tr><td>2014</td><td>26-Feb</td><td>Product</td><td>GitHub releases the initial version of Atom, a free and open-source text and source code editor.</td></tr>
<tr><td>2014</td><td>06-May</td><td>Product</td><td>GitHub fully releases the source code of its text editor Atom. Previously, many of its libraries and packages were open source, but the editor itself was not.</td></tr>
<tr><td>2014</td><td>07-Oct</td><td>Product</td><td>GitHub announces the GitHub Student Developer Pack, which gives students access to various premium services from GitHub and other tech companies.</td></tr>
<tr><td>2015</td><td>30-Apr</td><td>Company</td><td>At the conference Build 2015, Microsoft announces that Microsoft Visual Studio 2015 will have GitHub integrations, and that GitHub Enterprise would become available on Microsoft Azure.</td></tr>
<tr><td>2015</td><td>24-Sep</td><td>Company</td><td>Chris Wanstrath, co-founder and CEO of GitHub, is named as one of the Fortune 40 under 40.</td></tr>
<tr><td>2015</td><td>26-Mar</td><td>Censorship</td><td>GitHub falls victim to a massive distributed denial-of-service (DDOS) attack that lasts for more than 118 hours. The attack, which appeared to originate from China, primarily targeted GitHub-hosted user content describing methods of circumventing Internet censorship.</td></tr>
<tr><td>2015</td><td>03-Jun</td><td>Company</td><td>GitHub announces the formation of GitHub Japan G.K., a subsidiary of GitHub, Inc., as well as its new office in Tokyo, Japan. This new office is the first GitHub office outside of the United States.</td></tr>
<tr><td>2015</td><td>March</td><td>Product</td><td>Google announces that it would be closing down Google Code on January 15, 2016.[107] Most projects on the site would enter read-only mode on August 24, 2015.</td></tr>
<tr><td>2015</td><td>25-Jul</td><td>Company</td><td>GitHub announces it has raised $250 million in funding in a round led by Sequoia Capital. The round valued the company at approximately $2 billion.</td></tr>
<tr><td>2015</td><td>07-Feb</td><td>Growth</td><td>At this time, GitHub has 257 employees.</td></tr>
<tr><td>2015</td><td>15-Aug</td><td>Growth</td><td>At this time, GitHub has 330 employees.</td></tr>
<tr><td>2015</td><td>30-Mar</td><td>Growth</td><td>GitHub reports having over 9 million users and over 21.1 million repositories, making it the largest host of source code in the world.</td></tr>
<tr><td>2015</td><td>01-Sep</td><td>Growth</td><td>At this time, GitHub has around 10 million users.</td></tr>
<tr><td>2015</td><td>01-Sep</td><td>Growth</td><td>Around this time, 10,000 users are reportedly joining GitHub per weekday.</td></tr>
<tr><td>2015</td><td>28-Jan</td><td>Product</td><td>GitHub announces that it has doubled its maximum payout for its bounty program to $10,000.</td></tr>
<tr><td>2015</td><td>08-Apr</td><td>Product</td><td>GitHub announces Git Large File Storage (Git LFS). Git LFS allows users to store and work with large binary files in Git.</td></tr>
<tr><td>2015</td><td>19-May</td><td>Product</td><td>GitHub launches the GitHub Engineering blog, which hosts information about GitHub's engineering practices.</td></tr>
<tr><td>2015</td><td>25-Jun</td><td>Product</td><td>GitHub releases version 1.0 of its Atom text editor.</td></tr>
<tr><td>2015</td><td>12-Aug</td><td>Product</td><td>GitHub launches a desktop client for working with the site, for macOS and Microsoft Windows.</td></tr>
<tr><td>2015</td><td>22-Sep</td><td>Product</td><td>GitHub launches GitHub Classroom, a way for teachers to create and share programming assignments.</td></tr>
<tr><td>2015</td><td>01-Oct</td><td>Product</td><td>GitHub announces a partnership with Yubico to allow YubiKey authentication on the GitHub website.</td></tr>
<tr><td>2015</td><td>02-Feb</td><td>Userbase</td><td>The Office of Management and Budget releases budget data for fiscal years 2016 and 2017.</td></tr>
<tr><td>2015</td><td>03-Dec</td><td>Userbase</td><td>Apple open-sources its programming language Swift and hosts it on GitHub. This also marks the beginning of Apple using GitHub, as the company did not host anything on GitHub prior to this.</td></tr>
<tr><td>2016</td><td>07-Sep</td><td>Company</td><td>GitHub is ranked #14 on the Forbes Cloud 100 list.</td></tr>
<tr><td>2016</td><td>08-Oct</td><td>Company</td><td>GitHub access is blocked by the Turkish government to prevent email leakage of a hacked account belonging to the country's Energy Minister.</td></tr>
<tr><td>2016</td><td>05-Apr</td><td>Company</td><td>GitHub announces Spokes (called Distributed Git or DGit at the time), GitHub's application-level replication system for Git, which makes GitHub more resilient to server outages.</td></tr>
<tr><td>2016</td><td>17-May</td><td>Growth</td><td>At this time, GitHub has 568 employees.</td></tr>
<tr><td>2016</td><td>24-Dec</td><td>Growth</td><td>At this time, GitHub has 592 employees.</td></tr>
<tr><td>2016</td><td>28-Jan</td><td>Growth</td><td>At this time, there are over 29 million repositories on GitHub.</td></tr>
<tr><td>2016</td><td>28-Mar</td><td>Growth</td><td>GitHub announces that Atom, a text editor it created, has hit 1 million monthly active users. GitHub knows this number because Atom comes with a package called metrics that tracks usage information using Google Analytics and sends it to GitHub.</td></tr>
<tr><td>2016</td><td>09-May</td><td>Product</td><td>Version 1 of Electron is released.</td></tr>
<tr><td>2016</td><td>10-May</td><td>Product</td><td>GitHub introduces unlimited private repositories as it changes its pricing model from a repository-based one to a user-based one.</td></tr>
<tr><td>2016</td><td>06-Jul</td><td>Userbase</td><td>Nike, Inc. releases the source code of several of its projects on GitHub.</td></tr>
<tr><td>2017</td><td>14-Feb</td><td>Product</td><td>GitHub launches the Open Source Guides at the dedicated domain name opensource.guide.</td></tr>
<tr><td>2018</td><td>04-Jun</td><td>Company</td><td>Microsoft announced it is acquiring GitHub.</td></tr>
<tr><td>2020</td><td>16-Mar</td><td>Company</td><td>GitHub announced that they are acquiring npm.</td></tr></table>

'''
